name: Binaries - Windows x86

env:
    output_basename: sqlite3-windows-x86
    compilation_options: |
                    -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT \
                    -DSQLITE_ENABLE_DBSTAT_VTAB \
                    -DSQLITE_ENABLE_BYTECODE_VTAB \
                    -DSQLITE_ENABLE_COLUMN_METADATA \
                    -DSQLITE_ENABLE_EXPLAIN_COMMENTS \
                    -DSQLITE_ENABLE_FTS3 \
                    -DSQLITE_ENABLE_FTS4 \
                    -DSQLITE_ENABLE_FTS5 \
                    -DSQLITE_ENABLE_GEOPOLY \
                    -DSQLITE_ENABLE_JSON1 \
                    -DSQLITE_ENABLE_RTREE \
                    -DSQLITE_ENABLE_MATH_FUNCTIONS

on:
    workflow_dispatch:
        inputs:
          INT_VER:
            description: 'SQLite version as integer'
            required: true
            type: number
          PARENT_RUN_ID:
            description: 'ID of workflow that created appropriate amalgamation artifact'
            required: true
            type: number

jobs:
    build:
        runs-on: windows-2019

        steps:
            - name: Set up MinGW
              uses: egor-tensin/setup-mingw@v2
              with:
                platform: x86
                version: 8.1.0

            - name: Download Amalgamation
              shell: bash
              run: |
                set -x
                URL=$(
                    curl -s -L \
                        -H "Accept: application/vnd.github+json" \
                        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        -H "X-GitHub-Api-Version: 2022-11-28" \
                        https://api.github.com/repos/pawelsalawa/sqlite3-sqls/actions/runs/${{ inputs.PARENT_RUN_ID }}/artifacts \
                        | jq -r '.artifacts[0].archive_download_url'
                    )
                    
                ZIP_NAME=sqlite3-amalgamation-${{ inputs.INT_VER }}.zip
                echo "Downloading $ZIP_NAME from $URL"
                curl -s -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -o $ZIP_NAME $URL
                ls -l
                
                unzip $ZIP_NAME
                ls -l

                gcc sqlite3.c -Os -fpic -DWIN32 -m32 -I. -shared -o sqlite3.dll ${{ env.compilation_options }}
                gcc shell.c sqlite3.c -Os -fpic -DWIN32 -m32 -I. -o sqlite3.exe ${{ env.compilation_options }}
                ls -l

                OUTPUT_DIR=${{ env.output_basename }}-${{ inputs.INT_VER }}
                echo "OUTPUT_DIR=$OUTPUT_DIR" >> $GITHUB_ENV
                mkdir $OUTPUT_DIR
                cp sqlite3.dll sqlite3.exe sqlite3.h sqlite3ext.h $OUTPUT_DIR/
                
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.OUTPUT_DIR }}
                path: ${{ env.OUTPUT_DIR }}

